name: Sync and merge upstream repository
on:
  workflow_dispatch:
  schedule: 
  - cron: "0 8 * * *" #Runs at 8:00 UTC(5:00 in Korea) every day.

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name 'HamsterStudent'
          git config --global user.email 'hwanyamyu@gmail.com'
          # "git checkout master" is unnecessary, already here by default
          git pull --unshallow  # this option is very important, you would get
                                # complains about unrelated histories without it.
                                # (but actions/checkout@v2 can also be instructed
                                # to fetch all git depth right from the start)
          git remote add upstream https://github.com/Tinkerbell-Green/need-compliments.git
          git fetch upstream
          git checkout master
          git merge -Xtheirs upstream/master
          git push origin master
          # etc
